const constants = {
  SELECT_CARD: "SELECT_CARD",
  TOGGLE_NAME_EDIT: "TOGGLE_NAME_EDIT",
  EDIT_NAME: "EDIT_NAME",
  SELECT_NUM_PLAYERS: "SELECT_NUM_PLAYERS",
  SELECT_NUM_BANS: "SELECT_NUM_BANS",
  TOGGLE_SNAKE_DRAFT: "TOGGLE_SNAKE_DRAFT",
  CONFIRM_DRAFT_OPTIONS: "CONFIRM_DRAFT_OPTIONS",
  BAN_CARD: "BAN_CARD"
};

export default constants;